services:
  memdb:
    image: "geotool-memdb:1.0.0"
    ports:
      - "8004:6379"
  db:
    image: "geotool-db:1.0.0"
    ports:
      - "8003:5432"
    volumes:
      - /geotool-postgres-data:/var/lib/postgresql/data
  computer:
    image: "geotool-computer:0.1.0"
  pageserver:
    image: "geotool-pageserver:0.1.0"
    ports:
      - "8002:8002"
  haproxy:
    image: "geotool-haproxy:1.0.3"
    ports:
      - "443:443"

